fix: check `active` field when verifying access token
canfoundation/can-pass-verify pull request #7
Opened 2020-11-06 08:18 UTC by tiendq

in `canPass.verify(token)`

2020-11-06 10:33 UTC, manh-vv requested changes
Hi @tiendq, I reviewed with a request change. Please check.

2020-11-06 10:33 UTC, manh-vv commented on src/index.ts
> +active: true;
Isn't it expected?

2020-11-06 10:33 UTC, manh-vv commented on src/index.ts
> +  return result.active ? (result as VerifyOutput) : undefined;
Here, I would like to update:
* Keep using pure promise style.
* Throw an error if the access_token is not active.

```javascript
function verify(accessToken: string): Promise<VerifyOutput> {
  // handle case access-token start with `Bearer <access-token>`
  const _accessToken = accessToken.split(' ')[1] || accessToken;

  return _app
    .fetch(`${_app.canPassApi}/authenticate?access_token=${_accessToken}`)
    .then(checkFetchStatus)
    .then(res => res.json())
    .then(res => {
      if (!res.active) {
        throw new Error('Access token is not active.');
      }
      return res;
    });
}
```

2020-11-09 03:40 UTC, tiendq commented on src/index.ts
> +active: true;
Copy/paste mistake :(. Thanks.

2020-11-09 03:42 UTC, manh-vv approved these changes

2020-11-09 03:43 UTC, merged